### ISSUE TITLE
test

### ISSUE THREAD

**Issue by LoneDev6** [Andre601/Issues-ItemsAdder#2] opened 2024-09-02 13:06 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

aa

### Steps to reproduce the issue

aa

### Server version

aa

### ItemsAdder Version

aa

### ProtocolLib Version

aa

### LoneLibs Version

aa

### Full Server Log

aa

### Error (optional)

```shell
aa
```

**Comment by LoneDev6** [comment] 2024-09-02 13:07
Duplicate of #1

**Comment by Andre601** [comment] 2024-09-02 13:14
Duplicate of #1

**Comment by Andre601** [comment] 2024-09-02 15:56
Testing some changes...

Duplicate of

**Comment by Andre601** [comment] 2024-09-02 16:11
Duplicate of

**Comment by Andre601** [comment] 2024-09-02 16:17
Duplicate of

**Comment by Andre601** [comment] 2024-09-02 16:21
still not working yet and I'm out of ideas...

Duplicate of

**Comment by Andre601** [comment] 2024-09-02 17:53
Duplicate of

**Comment by Andre601** [comment] 2024-09-02 17:56
Testing a final time for consistency...

Duplicate of

**Closed** 2024-09-02 17:57 UTC
Labels: type: duplicate
